service: hola-mundo

provider:
  name: aws
  runtime: nodejs14.x

plugins:
  - serverless-offline

functions:
  hello-hour:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: GET
